name: [deploymentName]
director_uuid: [directorUuid]
release:
  version: [releaseVersion]
networks:
  default:
    subnets:
    - range: [subnetRange]
      gateway: [subnetGateway]
      dns: [[subnetDns]]
      static: [[subnetStatic]]
      reserved: [[subnetReserved]]
      cloud_properties:
        net_id: [subnetId]
jobs:
  director:
    networks:
      elastic:
        static_ips: [[publicStaticIp]]
resource_pools:
  small:
    stemcell:
      name: [stemcellName]
      version: [stemcellVersion]
    cloud_properties:
      instance_type: [smallInstanceType]
  medium:
    stemcell:
      name: [stemcellName]
      version: [stemcellVersion]
    env:
      bosh:
        password: [boshPassword]
    cloud_properties:
      instance_type: [directorInstanceType]
properties:
#  ntp: [[ntp]]
  openstack:
    auth_url: [authUrl]
    tenant: [tenant]
    username: [userName]
    api_key: [apiKey]
    default_key_name: [privateKeyName]
#   private_key: [privateKeyPath]
    default_security_groups: [[defaultSecurityGroups]]